name: SimpleTimer
version: ${version}
main: de.codecrafter.simpleTimer.SimpleTimer
api-version: '1.21'
authors: [ IschdeFelin ]
website: https://github.com/IschdeFelin
commands:
  timer:
    description: Controls the simple timer (pause, resume, reset, reload, set)
    usage: /timer <pause|resume|reset|reload|set> [time_in_seconds]
